nsupd: Implement `server' command handler [0.1.1]

diff --git a/nsupd b/nsupd
--- a/nsupd
+++ b/nsupd
@@ -3,7 +3,7 @@
 #
 # $Title: Script to make dynamic changes to nsadmin $
 # $Copyright: 2019 Devin Teske. All rights reserved. $
-# $FrauBSD: nsadmin/nsupd 2019-11-04 15:07:17 -0800 freebsdfrau $
+# $FrauBSD: nsadmin/nsupd 2019-11-07 14:09:40 -0800 freebsdfrau $
 #
 ############################################################ CONFIGURATION
 
@@ -15,7 +15,7 @@ DEFAULT_TIMEOUT=300
 
 ############################################################ GLOBALS
 
-VERSION='$Version: 0.1 $'
+VERSION='$Version: 0.1.1 $'
 
 pgm="${0##*/}" # Program basename
 
@@ -43,6 +43,7 @@ TIMEOUT=$DEFAULT_TIMEOUT	# -t timeout
 # Miscellaneous
 #
 PROMPT="> "
+SERVER=
 
 ############################################################ FUNCTIONS
 
@@ -284,9 +285,13 @@ handle_server()
 {
 	local cmd=server
 
-	printf "%s: %s: Implementation pending\n" "$pgm" "$cmd" >&2
+	if [ "$LOCAL" ]; then
+		echo "cannot reset server in localhost-only mode" >&2
+		return $SUCCESS # Non-fatal
+	fi
 
-	return $SUCCESS # Non-fatal
+	SERVER="$1"
+	# Remaining arguments silently ignored
 }
 
 # handle_update [$args ...]
