nsupd: Incremental commit [0.1.8]

diff --git a/nsupd b/nsupd
--- a/nsupd
+++ b/nsupd
@@ -3,7 +3,7 @@
 #
 # $Title: Script to make dynamic changes to nsadmin $
 # $Copyright: 2019 Devin Teske. All rights reserved. $
-# $FrauBSD: nsadmin/nsupd 2019-11-08 09:03:58 -0800 freebsdfrau $
+# $FrauBSD: nsadmin/nsupd 2019-11-13 14:01:49 -0800 freebsdfrau $
 #
 ############################################################ CONFIGURATION
 
@@ -16,9 +16,12 @@ DEFAULT_TIMEOUT=300
 # Default port for ssh command used by send processor
 DEFAULT_PORT=22
 
+# Default keyfile for ssh command used by send processor
+DEFAULT_SSHKEY=~/.ssh/id_rsa
+
 ############################################################ GLOBALS
 
-VERSION='$Version: 0.1.7 $'
+VERSION='$Version: 0.1.8 $'
 
 pgm="${0##*/}" # Program basename
 
@@ -41,6 +44,7 @@ FAILURE=1
 DEBUG=0				# -d | -D
 INTERACTIVE=1			# -i
 LOCAL=				# -l
+SSHKEY="$DEFAULT_SSHKEY"	# -k keyfile
 TIMEOUT=$DEFAULT_TIMEOUT	# -t timeout
 
 #
@@ -51,6 +55,7 @@ FILE=
 #
 # Miscellaneous
 #
+INPUT=
 NCMDS=0
 PORT=$DEFAULT_PORT
 PROMPT="> "
@@ -71,7 +76,7 @@ die()
 	local fmt="$1"
 	if [ $# -gt 0 ]; then
 		shift 1 # fmt
-		printf "%s: $fmt\n" "$pgm" "$@" >&2
+		printf "$fmt\n" "$@" >&2
 	fi
 	exit $FAILURE
 }
@@ -94,8 +99,9 @@ usage()
 	printf "Options:\n"
 	printf "$optfmt" "-d" "Debug mode."
 	printf "$optfmt" "-D" "Extra debug mode."
-	printf "$optfmt" "-i" "Force interactive mode."
 	printf "$optfmt" "-h" "Print usage statement and exit."
+	printf "$optfmt" "-i" "Force interactive mode."
+	printf "$optfmt" "-k keyfile" "SSH key. Default $DEFAULT_SSHKEY."
 	printf "$optfmt" "-l" "Local-host only mode."
 	printf "$optfmt" "-p port" "Port to connect on. Default $DEFAULT_PORT."
 	printf "$optfmt" "-t timeout" \
@@ -103,7 +109,6 @@ usage()
 	printf "$optfmt" "-V" "Print version and exit."
 	printf "Ignored Options (for compatibility):\n"
 	printf "$optfmt" "-g" "Not implemented."
-	printf "$optfmt" "-k keyfile" "Not implemented."
 	printf "$optfmt" "-L level" "Not implemented."
 	printf "$optfmt" "-o" "Not implemented."
 	printf "$optfmt" "-P" "Not implemented. Silently exits."
@@ -229,12 +234,11 @@ user_process()
 {
 	local cmd args
 
-	xdebug "user_interaction()"
-
 	while :; do
 		printf "%s" "$PROMPT"
 		read cmd args || break
 		one_process "$cmd" "$args"
+		xdebug "do_next_command()"
 	done
 }
 
@@ -278,12 +282,12 @@ send_server()
 	fi
 	
 	echo "$INPUT" | awk '
-		{ cmd = tolower($1) }
-		cmd == "server" { next }
+		$1 == "server" { next }
 		{ print }
 	' | ssh -oStrictHostKeyChecking=no \
 		-oBatchMode=yes \
 		-oPasswordAuthentication=no \
+		-i "$SSHKEY" \
 		"root@$SERVER" \
 		/usr/local/bin/nsupd $xtra -l -
 
@@ -434,16 +438,17 @@ handle_answer()
 #
 # Process command-line options
 #
-optign=gk:L:or:R:u:vy:
+optign=gL:or:R:u:vy:
 optignx=PT
-while getopts dDihlp:t:V$optign$optignx flag; do
+while getopts dDhik:lp:t:V$optign$optignx flag; do
 	case "$flag" in
-	g|k|L|o|r|R|u|v|y) : ignored ;;
+	g|L|o|r|R|u|v|y) : ignored ;;
 	d) [ $DEBUG -lt 1 ] && DEBUG=1 ;;
 	D) [ $DEBUG -lt 2 ] && DEBUG=2 ;;
 	p) PORT="$OPTARG" ;;
 	P|T) exit $SUCCESS ;; # Not implemented
 	i) INTERACTIVE=1 ;;
+	k) SSHKEY="$OPTARG" ;;
 	l) LOCAL=1 ;;
 	t) TIMEOUT="$OPTARG" ;;
 	V) VERSION="${VERSION#*: }"
@@ -457,21 +462,17 @@ shift $(( $OPTIND - 1 ))
 #
 # Validate command-line options
 #
-case "$TIMEOUT" in
-""|*[!0-9]*)
-	usage "\`-t timeout' requires a numerical argument" ;; # NOTREACHED
-esac
-case "$PORT" in
-""|*[!0-9]*)
-	usage "\`-p port' requires a numerical argument" ;; # NOTREACHED
-esac
-
 xdebug "setup_system()"
+[ "$LOCAL" -o -e "$SSHKEY" ] ||
+	die "can't read key from %s: file not found\n" "$SSHKEY"
+case "$TIMEOUT" in ""|*[!0-9]*) die "bad timeout '%s'" "$TIMEOUT" ;; esac
+case "$PORT" in ""|*[!0-9]*) die "bad port number '%s'" "$PORT" ;; esac
 xdebug "reset_system()"
 
 #
 # Process desired input
 #
+xdebug "user_interaction()"
 if [ $# -gt 0 ]; then
 	FILE="$1"
 	INTERACTIVE=
@@ -483,7 +484,6 @@ else
 fi
 
 xdebug "shutdown_program()"
-
 exit $SUCCESS
 
 ################################################################################
